#!/bin/bash

function install() {
  # Install vim-plug
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

	rsync --exclude ".DS_Store" -avh --no-perms . ~

	chsh -s /bin/zsh
	source ~/.zshrc
  vim -u ~/.quartercastle/vim/plug.vim +PlugInstall +qall
}


if [ "$1" == "--force" -o "$1" == "-f" ]; then
	install
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
	echo ""
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		install
	fi
fi
unset install
