#!/bin/bash

function install() {
	# TODO: Add option to build docker image on install
	# docker buildx build --platform linux/amd64 -t quartercastle .

	rsync --exclude ".DS_Store" -avh --no-perms . ~
	source ~/.zshrc
}


if [ "$1" == "--force" -o "$1" == "-f" ]; then
	install
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
	echo ""
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		install
	fi
fi
unset install
