#!/bin/bash
export TERM=xterm-256color
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# Paths
export PATH=/usr/local/bin:$PATH
export PATH=./node_modules/.bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/go/bin:$PATH
export PATH=~/go/bin:$PATH
export PATH=~/.quartercastle/bin:$PATH
export PATH="~/.cargo/bin:$PATH"
export PATH="~/.local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

# Default editor
export VISUAL=vim
export EDITOR="$VISUAL"

# Golang
export GOPRIVATE=github.com/DanaDynamics
